[package]
name = "example-common"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
tracing = "0.1.40"
mdns-sd = "0.11.5"
airplay = { path = "../../airplay/" }

gstreamer = "0.23.6"
gstreamer-app = "0.23.5"
